site_name: Antonio Cuni's blog
# ' this is for emacs, else it messes up syntax highlighting
site_url: https://antocuni.github.io/

docs_dir: blog

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - blog:
      blog_dir: .
      post_excerpt: required
      pagination: true
      post_url_format: "{date}/{slug}"
      post_date_format: medium

  - search

  - tags


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
