import os, time, math, random

def fn(v=None, a=None, b=None, c=None, d=None, e=None, f=None, g=None, h=None):
    """
    Random nonsense computation generated by ChatGPT
    """
    if v is None: v = 0
    if a is None: a = 1.25
    if b is None: b = -0.75
    if c is None: c = 0.33
    if d is None: d = 0.10
    if e is None: e = 1.5   # exponent
    if f is None: f = 0.0   # clamp min
    if g is None: g = 1.0   # clamp max
    if h is None: h = 0.5   # mix

    y = a * v + b
    y = math.copysign(abs(y) ** e, y)
    y = c * y + d
    if y < f: y = f
    if y > g: y = g
    y = h * y + (1.0 - h) * v
    y = y + 0.01 * math.sin(3.0 * y) - 0.01 * math.cos(2.0 * v)
    return y

def main():
    N = 1000000

    def rnd():
        return random.choice([None, random.random()])
        #return random.random()


    print('generating data...', end='', flush=True)
    DATA = [
        tuple(rnd() for _ in range(9))
        for _ in range(N)
    ]
    print()
    print('computing...')

    acc = 0
    start = time.time()
    for row in DATA:
        acc += fn(*row)
    end = time.time()
    print('%.4f secs' % (end - start))

if __name__ == "__main__":
    main()
